# Generated by Django 4.1.1 on 2022-09-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concrete_class', models.CharField(max_length=5, unique=True)),
                ('R_b_n', models.FloatField()),
                ('R_bt_n', models.FloatField()),
                ('R_b', models.FloatField()),
                ('R_bt', models.FloatField()),
                ('E_b', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_year', models.PositiveSmallIntegerField()),
                ('group_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reinforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reinforcement_class', models.CharField(max_length=8)),
                ('possible_diameters', models.CharField(max_length=20)),
                ('R_s_ser', models.PositiveSmallIntegerField()),
                ('R_s', models.PositiveSmallIntegerField()),
                ('R_sc_l', models.PositiveSmallIntegerField()),
                ('R_sc_sh', models.PositiveSmallIntegerField()),
                ('R_sw', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VariantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Family name, given name, patronymic (if acceptable)', max_length=300)),
                ('subgroup_variant_number', models.PositiveSmallIntegerField()),
                ('personal_variant_number', models.PositiveSmallIntegerField()),
                ('preferred_freefall_acceleration', models.FloatField(default=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autograder.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
