# Generated by Django 4.1.1 on 2022-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlabReferenceGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_length', models.SmallIntegerField()),
                ('nominal_width', models.SmallIntegerField()),
                ('nominal_height', models.SmallIntegerField()),
                ('load_greater_than', models.SmallIntegerField()),
                ('load_less_than', models.SmallIntegerField()),
                ('slab_fact_width_bottom', models.SmallIntegerField()),
                ('slab_fact_width_top', models.SmallIntegerField()),
                ('longitudinal_rib_width_bottom', models.SmallIntegerField()),
                ('longitudinal_rib_width_top', models.SmallIntegerField()),
                ('flange_height', models.SmallIntegerField()),
                ('transverse_rib_outer_width_bottom', models.SmallIntegerField()),
                ('transverse_rib_usual_height', models.SmallIntegerField()),
                ('transverse_rib_outer_width_top', models.SmallIntegerField()),
                ('transverse_rib_usual_width_bottom', models.SmallIntegerField()),
                ('transverse_rib_usual_width_top', models.SmallIntegerField()),
                ('transverse_ribs_spacing', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'autograder_slab_reference_geometry',
            },
        ),
        migrations.CreateModel(
            name='TrussName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truss_type', models.CharField(max_length=3)),
                ('frames_spacing', models.SmallIntegerField()),
                ('load_greater_than', models.SmallIntegerField()),
                ('load_less_than', models.SmallIntegerField()),
                ('truss_span', models.SmallIntegerField()),
                ('truss_name', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'autograder_truss_name',
            },
        ),
        migrations.CreateModel(
            name='TrussParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truss_name', models.CharField(max_length=6)),
                ('truss_length', models.SmallIntegerField()),
                ('truss_height', models.SmallIntegerField()),
                ('truss_mass', models.FloatField()),
                ('truss_width', models.SmallIntegerField()),
                ('top_chord_cross_section_height', models.SmallIntegerField()),
                ('bottom_chord_cross_section_height', models.SmallIntegerField()),
                ('bracing_elements_cross_section_height', models.SmallIntegerField()),
                ('bracing_elements_cross_section_height_extra', models.SmallIntegerField()),
                ('bearing_knot_height', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'autograder_truss_parameters',
            },
        ),
    ]
