# Generated by Django 4.1.1 on 2022-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='average_january_temp',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='snow_region',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='snow_region_2011',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='wind_region',
            field=models.SmallIntegerField(null=True),
        ),
    ]
